version: '3.8'
services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - adopet-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  adopet-data: